name: Prepare javascript dependencies without caching
description: Prepare mobile node modules, as well as webapp submodule

runs:
  using: composite
  steps:
    - name: Install webapp submodule
      run: |
        git submodule update --init --recursive
      shell: bash
    - name: Setup webapp node version
      uses: actions/setup-node@v2
      with:
        node-version: '12.19.1'
    - name: Clean npm cache
      run: |
        npm cache clean --force
    - name: Install webapp node_modules
      run: |
        cd webapp
        npm ci
        cd ..
      shell: bash
    - name: Setup mobileapp node version
      uses: actions/setup-node@v2
      with:
        node-version: '16.6.0'
    - name: Install mobile node_modules
      run: |
        export UV_THREADPOOL_SIZE=64
        yarn install --frozen-lockfile --network-concurrency 8 --network-timeout 1000000
      shell: bash
