name: Prepare javascript dependencies
description: Prepare mobile node modules, as well as webapp submodule

runs:
  using: composite
  steps:
    - name: Set node version
      uses: actions/setup-node@v2
      with:
        node-version: '12.19.1'

    - name: Install submodules
      run: |
        git submodule update --init --recursive
        cd webapp
        npm install
        cd ..
      shell: bash

    - name: Set node version for mobile
      uses: actions/setup-node@v2
      with:
        node-version: '10.17.0'

    - name: Install dependencies
      run: yarn install --frozen-lockfile --network-timeout 1000000
      shell: bash
