name: Prepare javascript dependencies
description: Prepare mobile node modules, as well as webapp submodule

env:
  WEBAPP_NODE_VERSION: '12.19.1'
  MOBILE_NODE_VERSION: '16.6.0'

runs:
  using: composite
  steps:
    - name: Install nvm and node
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install $MOBILE_NODE_VERSION
        nvm install $WEBAPP_NODE_VERSION
        nvm use $WEBAPP_NODE_VERSION
      shell: bash -l -eo pipefail {0}

    - name: Install submodules
      run: |
        git submodule update --init --recursive
        cd webapp
        npm install
        cd ..
      shell: bash -l -eo pipefail {0}

    - name: Install mobile dependencies
      run: |
        nvm use $MOBILE_NODE_VERSION
        yarn install --frozen-lockfile --network-timeout 1000000
      shell: bash -l -eo pipefail {0}
