name: Prepare javascript dependencies
description: Prepare mobile node modules, as well as webapp submodule

inputs:
  cache-enabled:
    description: Enable caching
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install webapp submodule
      run: |
        git submodule update --init --recursive
      shell: bash
    - name: Setup webapp node version
      uses: actions/setup-node@v2
      with:
        node-version: '12.19.1'
        cache: 'npm'
        cache-dependency-path: webapp/package-lock.json
    - name: Cache webapp node_modules
      uses: actions/cache@v2
      id: webapp-node-cache
      with:
        path: webapp/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('webapp/package-lock.json') }}
    - name: Install webapp node_modules
      if: steps.webapp-node-cache.outputs.cache-hit != 'true'
      run: |
        cd webapp
        npm ci
        cd ..
      shell: bash
    - name: Setup mobileapp node version
      uses: actions/setup-node@v2
      with:
        node-version: '16.6.0'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
    - name: Cache mobileapp node_modules
      uses: actions/cache@v2
      id: mobileapp-node-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
    - name: Install mobile node_modules
      if: steps.mobileapp-node-cache.outputs.cache-hit != 'true'
      run: |
        export UV_THREADPOOL_SIZE=64
        yarn install --frozen-lockfile --network-concurrency 8 --network-timeout 1000000
      shell: bash
